// PLACEHOLDER DATA — prices, parameter counts and inclusions are illustrative. Replace with the lab's real list before launch. Medical wording must be confirmed by the lab.
window.TESTS_CATALOGUE = {
  en: [
    { id: 'cbc', name: 'CBC', price: 300, sample: 'Blood', reports: 'Same day', category: 'Blood', concern: 'General' },
    { id: 'hemoglobin', name: 'Hemoglobin', price: 80, sample: 'Blood', reports: 'Same day', category: 'Blood', concern: 'Anemia' },
    { id: 'esr', name: 'ESR', price: 100, sample: 'Blood', reports: 'Same day', category: 'Blood', concern: 'Fever/Infection' },
    { id: 'fasting-blood-sugar', name: 'Fasting Blood Sugar', price: 60, sample: 'Blood', reports: 'Same day', category: 'Diabetes', concern: 'Diabetes' },
    { id: 'pp-blood-sugar', name: 'PP Blood Sugar', price: 60, sample: 'Blood', reports: 'Same day', category: 'Diabetes', concern: 'Diabetes' },
    { id: 'hba1c', name: 'HbA1c', price: 500, sample: 'Blood', reports: '24 hrs', category: 'Diabetes', concern: 'Diabetes' },
    { id: 'lipid-profile', name: 'Lipid Profile', price: 500, sample: 'Blood', reports: '24 hrs', category: 'Heart', concern: 'Heart' },
    { id: 'liver-function', name: 'Liver Function', price: 500, sample: 'Blood', reports: '24 hrs', category: 'Liver', concern: 'Liver' },
    { id: 'kidney-function', name: 'Kidney Function', price: 450, sample: 'Blood', reports: '24 hrs', category: 'Kidney', concern: 'Kidney' },
    { id: 'thyroid-profile', name: 'Thyroid Profile (T3/T4/TSH)', price: 500, sample: 'Blood', reports: '24 hrs', category: 'Thyroid', concern: 'Thyroid' },
    { id: 'tsh', name: 'TSH', price: 300, sample: 'Blood', reports: '24 hrs', category: 'Thyroid', concern: 'Thyroid' },
    { id: 'vitamin-d', name: 'Vitamin D', price: 1200, sample: 'Blood', reports: '24 hrs', category: 'Vitamin', concern: 'Vitamins' },
    { id: 'vitamin-b12', name: 'Vitamin B12', price: 800, sample: 'Blood', reports: '24 hrs', category: 'Vitamin', concern: 'Vitamins' },
    { id: 'urine-routine', name: 'Urine Routine', price: 100, sample: 'Urine', reports: 'Same day', category: 'Urine', concern: 'Urine & Stool Infection' },
    { id: 'urine-culture-sensitivity', name: 'Urine Culture & Sensitivity', price: 450, sample: 'Urine', reports: '24–48 hrs', category: 'Urine', concern: 'Urine & Stool Infection' },
    { id: 'stool-routine', name: 'Stool Routine', price: 100, sample: 'Stool', reports: '24 hrs', category: 'Stool', concern: 'Urine & Stool Infection' },
    { id: 'widal', name: 'Widal', price: 250, sample: 'Blood', reports: 'Same day', category: 'Infection', concern: 'Fever/Infection' },
    { id: 'malaria-test', name: 'Malaria Test', price: 250, sample: 'Blood', reports: 'Same day', category: 'Infection', concern: 'Fever/Infection' },
    { id: 'dengue-ns1', name: 'Dengue NS1', price: 700, sample: 'Blood', reports: '24 hrs', category: 'Infection', concern: 'Fever/Infection' },
    { id: 'crp', name: 'CRP', price: 450, sample: 'Blood', reports: '24 hrs', category: 'Inflammation', concern: 'Fever/Infection' },
    { id: 'sputum-afb', name: 'Sputum AFB Smear', price: 200, sample: 'Sputum', reports: '24 hrs', category: 'Microbiology', concern: 'Fever/Infection' },
    { id: 'blood-group', name: 'Blood Group', price: 100, sample: 'Blood', reports: 'Same day', category: 'General', concern: 'General' }
  ],
  mr: [
    { id: 'cbc', name: 'सीबीसी', price: 300, sample: 'रक्त', reports: 'त्याच दिवशी', category: 'रक्त', concern: 'सामान्य' },
    { id: 'hemoglobin', name: 'हीमोग्लोबिन', price: 80, sample: 'रक्त', reports: 'त्याच दिवशी', category: 'रक्त', concern: 'अनिमिया' },
    { id: 'esr', name: 'ईएसआर', price: 100, sample: 'रक्त', reports: 'त्याच दिवशी', category: 'रक्त', concern: 'ज्वर/संक्रमण' },
    { id: 'fasting-blood-sugar', name: 'उपवास साखर', price: 60, sample: 'रक्त', reports: 'त्याच दिवशी', category: 'डायबेटीज', concern: 'डायबेटीज' },
    { id: 'pp-blood-sugar', name: 'PP साखर', price: 60, sample: 'रक्त', reports: 'त्याच दिवशी', category: 'डायबेटीज', concern: 'डायबेटीज' },
    { id: 'hba1c', name: 'HbA1c', price: 500, sample: 'रक्त', reports: '२४ तास', category: 'डायबेटीज', concern: 'डायबेटीज' },
    { id: 'lipid-profile', name: 'लिपिड प्रोफाइल', price: 500, sample: 'रक्त', reports: '२४ तास', category: 'हृदय', concern: 'हृदय' },
    { id: 'liver-function', name: 'यकृत कार्य', price: 500, sample: 'रक्त', reports: '२४ तास', category: 'यकृत', concern: 'यकृत' },
    { id: 'kidney-function', name: 'किडनी कार्य', price: 450, sample: 'रक्त', reports: '२४ तास', category: 'किडनी', concern: 'किडनी' },
    { id: 'thyroid-profile', name: 'थायरॉईड प्रोफाइल (T3/T4/TSH)', price: 500, sample: 'रक्त', reports: '२४ तास', category: 'थायरॉईड', concern: 'थायरॉईड' },
    { id: 'tsh', name: 'TSH', price: 300, sample: 'रक्त', reports: '२४ तास', category: 'थायरॉईड', concern: 'थायरॉईड' },
    { id: 'vitamin-d', name: 'व्हिटामिन डी', price: 1200, sample: 'रक्त', reports: '२४ तास', category: 'व्हिटामिन', concern: 'व्हिटामिन' },
    { id: 'vitamin-b12', name: 'व्हिटामिन B12', price: 800, sample: 'रक्त', reports: '२४ तास', category: 'व्हिटामिन', concern: 'व्हिटामिन' },
    { id: 'urine-routine', name: 'मूत्र रूटीन', price: 100, sample: 'मूत्र', reports: 'त्याच दिवशी', category: 'मूत्र', concern: 'मूत्र व मल संसर्ग' },
    { id: 'urine-culture-sensitivity', name: 'मूत्र कल्चर आणि सेन्सिटिव्हिटी', price: 450, sample: 'मूत्र', reports: '२४–४८ तास', category: 'मूत्र', concern: 'मूत्र व मल संसर्ग' },
    { id: 'stool-routine', name: 'मल रूटीन', price: 100, sample: 'मल', reports: '२४ तास', category: 'मल', concern: 'मूत्र व मल संसर्ग' },
    { id: 'widal', name: 'विडाल', price: 250, sample: 'रक्त', reports: 'त्याच दिवशी', category: 'संसर्ग', concern: 'ज्वर/संक्रमण' },
    { id: 'malaria-test', name: 'मलेरिया टेस्ट', price: 250, sample: 'रक्त', reports: 'त्याच दिवशी', category: 'संसर्ग', concern: 'ज्वर/संक्रमण' },
    { id: 'dengue-ns1', name: 'डेंग्यू NS1', price: 700, sample: 'रक्त', reports: '२४ तास', category: 'संसर्ग', concern: 'ज्वर/संक्रमण' },
    { id: 'crp', name: 'CRP', price: 450, sample: 'रक्त', reports: '२४ तास', category: 'दाह', concern: 'ज्वर/संक्रमण' },
    { id: 'sputum-afb', name: 'सप्युम AFB स्मीयर', price: 200, sample: 'सप्युम', reports: '२४ तास', category: 'माइक्रोबायोलॉजी', concern: 'ज्वर/संक्रमण' },
    { id: 'blood-group', name: 'रक्त गट', price: 100, sample: 'रक्त', reports: 'त्याच दिवशी', category: 'सामान्य', concern: 'सामान्य' }
  ]
};
